### ISSUE TITLE
Cannot perform npm install

### ISSUE THREAD

**Issue by imerei** [benmonro/android#1]
Hey guys, I would like to install the android node but I am getting the following message when I try <b>npm install android</b> and <b>npm install -g android</b>:

```
npm ERR! fetch failed https://registry.npmjs.org/android/-/android-0.0.7.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/android/-/android-0.0.7.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/android/-/android-0.0.7.tgz
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "android"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5

npm ERR! fetch failed with status code 404
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Please assist. Thanks!

**Comment by benmonro** [comment]
@imerei I haven't touched this code in about 2 years.  Feel free to submit a pull request and I will accept it and publish it to npm.  Or alternatively you can clone the github repo locally and then do npm install ./path/to/android

**Comment by imerei** [comment]
@benmonro I decided to locally clone the repo and it works as expected. Thank you for your assistance.
